In [1]:
import pandas as pd
from pathlib import Path
from algorithm.src.scoring.scoring import score_dataframe

In [2]:
df = pd.read_parquet("../../data/processed/site_features/property_site_features_v1_sample.parquet")
scored = score_dataframe(df)

print(len(scored))
scored.head()

49950

,RID,gurasid,propertytype,valnetpropertystatus,valnetpropertytype,dissolveparcelcount,valnetlotcount,propid,superlot,address,...,log_distance_to_station_m,station_access_score,station_distance_bucket,single_dwelling_rebuild_score,assembly_opportunity_score,granny_flat_score,land_bank_hold_score,townhouse_multi_dwelling_score,low_rise_apartment_score,dual_occupancy_score
0,260,49494103,1,2.0,2.0,1,1,1341,N,44 NORTHCOTE STREET ABERDARE,...,9.806382,0.000055,>10km,70.0,12.0,70.0,45.0,22.0,1.0,70.0
1,319,49494159,1,2.0,2.0,1,1,3169,N,10 MEREWETHER CLOSE NORTH ROTHBURY,...,8.129650,0.000295,2km-5km,45.2,19.6,53.5,29.6,19.0,13.5,38.8
2,327,49494166,1,2.0,2.0,1,1,3682,N,112 MATHIESON STREET BELLBIRD HEIGHTS,...,9.958687,0.000047,>10km,70.0,12.0,70.0,45.0,22.0,1.0,60.0
3,338,49494176,1,2.0,2.0,1,1,3958,N,584 WOLLOMBI ROAD BELLBIRD,...,10.104941,0.000041,>10km,32.0,6.0,11.5,17.0,1.0,0.5,11.5
4,359,49494197,1,2.0,2.0,1,1,4739,N,41 RUSSELL STREET BRANXTON,...,5.679883,0.003414,<=800m,61.0,43.0,62.5,78.0,65.0,47.5,64.0

In [3]:
score_cols = [c for c in scored.columns if c.endswith("_score")]
scored[score_cols].describe()

,station_access_score,single_dwelling_rebuild_score,assembly_opportunity_score,granny_flat_score,land_bank_hold_score,townhouse_multi_dwelling_score,low_rise_apartment_score,dual_occupancy_score
count,49950.000000,49950.000000,49950.000000,49950.000000,49950.000000,49950.000000,49950.000000,49950.000000
mean,0.001040,49.237257,29.867423,45.141540,45.129213,30.325726,23.230525,43.892156
std,0.002278,21.444702,20.514430,19.712135,19.639015,19.397848,21.948842,19.018280
min,0.000001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000039,33.000000,15.600000,32.000000,31.000000,16.000000,5.500000,31.000000
50%,0.000377,55.000000,25.000000,45.000000,44.000000,26.000000,14.000000,44.800000
75%,0.001006,70.000000,41.000000,59.000000,58.000000,42.000000,36.000000,57.300000
max,0.063341,81.000000,93.000000,82.500000,93.000000,90.000000,97.500000,84.000000

In [4]:
base_cols = [
    "RID",
    "address",
    "lot_size_proxy_sqm",
    "primary_zoning_code",
    "primary_zoning_class",
    "mixed_zoning_flag",
    "heritage_flag",
    "heritage_max_significance",
    "bushfire_flag",
    "bushfire_risk_level",
    "flood_flag",
    "primary_flood_class",
    "distance_to_station_m",
    "within_800m_catchment",
]

In [5]:
def inspect_strategy(df: pd.DataFrame, score_col: str, n: int = 20):
    print(f"\n=== TOP {n}: {score_col} ===")
    display(
        df.sort_values(score_col, ascending=False)[base_cols + [score_col]].head(n)
    )

    print(f"\n=== BOTTOM {n}: {score_col} ===")
    display(
        df.sort_values(score_col, ascending=True)[base_cols + [score_col]].head(n)
    )

In [6]:
inspect_strategy(scored, "single_dwelling_rebuild_score")

=== TOP 20: single_dwelling_rebuild_score ===

,RID,address,lot_size_proxy_sqm,primary_zoning_code,primary_zoning_class,mixed_zoning_flag,heritage_flag,heritage_max_significance,bushfire_flag,bushfire_risk_level,flood_flag,primary_flood_class,distance_to_station_m,within_800m_catchment,single_dwelling_rebuild_score
20260,2222615,53 COACHWOOD DRIVE WARABROOK,1248.808784,R2,Low Density Residential,1,0,None,0,0,0,None,632.077946,1,81.0
6476,709596,2 STRATFORD PARK DRIVE TERRIGAL,1407.799537,R2,Low Density Residential,1,0,None,0,0,0,None,148.580796,1,81.0
46865,7092139,2/144 KARIMBLA ROAD MIRANDA,2337.336723,R2,Low Density Residential,1,0,None,0,0,0,None,649.067709,1,81.0
8584,937377,14 LETITIA CLOSE GREEN POINT,936.793086,R2,Low Density Residential,1,0,None,0,0,0,None,372.439648,1,81.0
29888,3496205,7/34 ROWLAND AVENUE WOLLONGONG,2639.122712,R2,Low Density Residential,1,0,None,0,0,0,None,548.317157,1,81.0
15766,1727534,8/38-40 GOULD AVENUE LEWISHAM,1913.294007,R2,Low Density Residential,1,0,None,0,0,0,None,708.558592,1,81.0
7886,861436,2/11-13 PENKIVIL STREET BONDI,1276.265657,R2,Low Density Residential,1,0,None,0,0,0,None,376.731722,1,81.0
29625,3457081,305/35-37 RAWSON STREET AUBURN,2689.885642,R2,Low Density Residential,1,0,None,0,0,0,None,339.857479,1,81.0
6715,733330,2/14 EDENSOR STREET EPPING,2651.622161,R2,Low Density Residential,1,0,None,0,0,0,None,676.555819,1,81.0
16938,1861694,39 CAROLINE STREET EAST GOSFORD,2878.442060,R2,Low Density Residential,1,0,None,0,0,0,None,748.244762,1,81.0
27898,3215276,37/422-426 PEATS FERRY ROAD ASQUITH,3858.365619,R2,Low Density Residential,1,0,None,0,0,0,None,745.544478,1,81.0
27897,3215272,52/422-426 PEATS FERRY ROAD ASQUITH,3858.365619,R2,Low Density Residential,1,0,None,0,0,0,None,745.544478,1,81.0
15791,1731082,2/122 GARDEN STREET MAROUBRA,1237.454627,R2,Low Density Residential,1,0,None,0,0,0,None,244.941865,1,81.0
23717,2632596,2/5 STATION STREET THIRROUL,2210.817802,R2,Low Density Residential,1,0,None,0,0,0,None,179.270184,1,81.0
740,77979,21 FOREST WAY FRENCHS FOREST,1019.941461,R2,Low Density Residential,1,0,None,0,0,0,None,267.534308,1,81.0
3894,423138,23 ALICE STREET MACQUARIE FIELDS,867.328224,R2,Low Density Residential,1,0,None,0,0,0,None,571.053455,1,81.0
41740,6131866,9/147 PRESIDENT AVENUE MIRANDA,3290.077826,R2,Low Density Residential,1,0,None,0,0,0,None,780.595515,1,81.0
48956,7401424,4/139-145 TARGO ROAD GIRRAWEEN,4448.459005,R2,Low Density Residential,1,0,None,0,0,0,None,535.900501,1,81.0
7713,842268,16 CAMBRIDGE AVENUE WINDSOR,1178.372089,R2,Low Density Residential,1,0,None,0,0,0,None,421.861131,1,81.0
11809,1286256,1/685 OLD SOUTH HEAD ROAD VAUCLUSE,2232.669518,R2,Low Density Residential,1,0,None,0,0,0,None,88.528876,1,81.0

=== BOTTOM 20: single_dwelling_rebuild_score ===

,RID,address,lot_size_proxy_sqm,primary_zoning_code,primary_zoning_class,mixed_zoning_flag,heritage_flag,heritage_max_significance,bushfire_flag,bushfire_risk_level,flood_flag,primary_flood_class,distance_to_station_m,within_800m_catchment,single_dwelling_rebuild_score
38765,5444885,MOSS VALE ROAD KANGAROO VALLEY,4.492247e+05,SP2,Infrastructure,1,1,Local,1,3,0,None,19756.331460,0,0.0
13642,1490332,413 PARRAMATTA ROAD LEICHHARDT,3.032401e+02,E1,Local Centre,1,1,Local,0,0,0,None,779.413697,1,0.0
45147,6783595,279 BARRINGTON EAST ROAD BARRINGTON,2.823107e+05,RU1,Primary Production,0,1,Local,1,1,0,None,55444.566636,0,0.0
4784,525849,27 EMU SWAMP ROAD LUCKNOW,4.246200e+05,C3,Environmental Management,0,1,Local,1,3,0,None,47311.949976,0,0.0
34115,4359571,BURFITT PARADE GLENBROOK,5.930413e+04,C4,Environmental Living,1,1,Local,1,3,0,None,460.560235,1,0.0
34279,4405417,233/40 SHOALHAVEN HEADS ROAD SHOALHAVEN HEADS,1.528670e+05,RU2,Rural Landscape,1,1,Local,1,3,0,None,10329.524713,0,0.0
608,65134,5/31-33 SYDNEY ROAD MANLY,3.947931e+02,E1,Local Centre,0,1,Local,0,0,0,None,4641.545010,0,0.0
30486,3569726,5/31-65 YAMBA ROAD YAMBA,7.695128e+04,SP3,Tourist,1,0,None,1,3,1,Flood Planning Area,76638.966014,0,0.0
49573,7479805,78-80 OTHO STREET INVERELL,4.666728e+02,E2,Commercial Centre,0,1,Local,0,0,0,None,269766.271461,0,0.0
38586,5406460,PENNANT HILLS ROAD NORMANHURST,5.648098e+01,RE1,Public Recreation,1,1,Local,0,0,0,None,612.381549,1,0.0
31668,3758840,38/2-4 SUGAR HOUSE ROAD CANTERBURY,6.389325e+03,RE1,Public Recreation,1,1,State,0,0,0,None,2390.549524,0,0.0
27534,3157644,ILUKA ROAD ILUKA,4.561944e+05,RE2,Private Recreation,1,0,None,1,3,1,Flood Planning Area,70771.262927,0,0.0
31031,3666406,17 MANDAGERY ROAD MANDAGERY,8.749527e+06,RU1,Primary Production,0,1,Local,1,3,0,None,122093.853978,0,0.0
38890,5479207,463 LEEDS PARADE ORANGE,7.111677e+05,SP2,Infrastructure,1,1,Local,1,3,0,None,58248.971519,0,0.0
49568,7479064,66 WHARF STREET SOUTH GRAFTON,2.260634e+03,E3,Productivity Support,1,1,Local,0,0,1,Flood Planning Area,118513.049022,0,0.0
31183,3687716,3/13 CRINAN STREET HURLSTONE PARK,4.351078e+02,E1,Local Centre,0,1,Local,0,0,0,None,2647.561552,0,0.0
12146,1325191,632 SKYLINE ROAD GOONELLABAH,2.646617e+04,RU1,Primary Production,0,1,Local,1,2,0,None,1265.558743,0,0.0
37425,5130150,2/1110 MIDDLE HEAD ROAD MOSMAN,1.357661e+05,SP2,Infrastructure,1,1,State,1,3,0,None,3218.229093,0,0.0
42461,6276433,186 SOUTH STREET TERARA,3.049251e+04,RU1,Primary Production,0,1,Local,1,1,0,None,2970.391412,0,0.0
37427,5130351,110 MARBLE HILL ROAD KINGSDALE,5.887349e+05,C3,Environmental Management,0,1,Local,1,1,0,None,9484.839659,0,0.0

In [7]:
inspect_strategy(scored, "assembly_opportunity_score")

=== TOP 20: assembly_opportunity_score ===

,RID,address,lot_size_proxy_sqm,primary_zoning_code,primary_zoning_class,mixed_zoning_flag,heritage_flag,heritage_max_significance,bushfire_flag,bushfire_risk_level,flood_flag,primary_flood_class,distance_to_station_m,within_800m_catchment,assembly_opportunity_score
34518,4486964,203/782-822 BOURKE STREET WATERLOO,14817.434159,MU1,Mixed Use,1,0,None,0,0,0,None,688.883870,1,93.0
40577,5873424,1308/25 GEDDES AVENUE ZETLAND,7354.747241,MU1,Mixed Use,1,0,None,0,0,0,None,452.463369,1,93.0
44267,6623125,606/20 GERRALE STREET CRONULLA,4528.225448,E2,Commercial Centre,1,0,None,0,0,0,None,313.055779,1,93.0
44266,6623077,9/20 GERRALE STREET CRONULLA,4528.225448,E2,Commercial Centre,1,0,None,0,0,0,None,313.055779,1,93.0
20727,2275163,1803/41-45 WAITARA AVENUE WAITARA,6484.752655,R4,High Density Residential,1,0,None,0,0,0,None,466.372529,1,93.0
40224,5807067,27/60-66 AUBURN STREET SUTHERLAND,5029.920462,R4,High Density Residential,1,0,None,0,0,0,None,689.764095,1,93.0
928,100012,5 ST GEORGES ROAD PENSHURST,9648.214086,R4,High Density Residential,1,0,None,0,0,0,None,603.951467,1,93.0
42898,6364097,310/5 JOYNTON AVENUE ZETLAND,11507.113955,MU1,Mixed Use,1,0,None,0,0,0,None,523.852548,1,93.0
42899,6364171,309/5 JOYNTON AVENUE ZETLAND,11507.113955,MU1,Mixed Use,1,0,None,0,0,0,None,523.852548,1,93.0
9752,1063886,27/75-81 GLENCOE STREET SUTHERLAND,5819.749034,R4,High Density Residential,1,0,None,0,0,0,None,616.521914,1,93.0
40578,5873427,709/6 PAUL STREET ZETLAND,7354.747241,MU1,Mixed Use,1,0,None,0,0,0,None,452.463369,1,93.0
40196,5804324,56/61-65 GLENCOE STREET SUTHERLAND,5074.581240,R4,High Density Residential,1,0,None,0,0,0,None,620.568563,1,93.0
40579,5873439,807/6 PAUL STREET ZETLAND,7354.747241,MU1,Mixed Use,1,0,None,0,0,0,None,452.463369,1,93.0
7042,766890,79/4 CLARK ROAD NORTH SYDNEY,5604.520988,R4,High Density Residential,1,0,None,0,0,0,None,456.733062,1,93.0
47071,7121350,4214/834 PITTWATER ROAD DEE WHY,14376.765789,MU1,Mixed Use,1,0,None,0,0,0,None,744.279176,1,93.0
40580,5873483,201/6 PAUL STREET ZETLAND,7354.747241,MU1,Mixed Use,1,0,None,0,0,0,None,452.463369,1,93.0
23227,2563843,145 GEORGE STREET MARULAN,11936.185108,E3,Productivity Support,1,0,None,0,0,0,None,798.879288,1,93.0
40595,5875089,306/39-47 ORARA STREET WAITARA,5194.122364,R4,High Density Residential,1,0,None,0,0,0,None,502.323283,1,93.0
8453,922844,24/72-78 CONSTITUTION ROAD WEST MEADOWBANK,5079.619668,R4,High Density Residential,1,0,None,0,0,0,None,198.391758,1,93.0
40126,5788353,302/33 THE GRAND PARADE SUTHERLAND,6925.264118,R4,High Density Residential,1,0,None,0,0,0,None,463.340068,1,93.0

=== BOTTOM 20: assembly_opportunity_score ===

,RID,address,lot_size_proxy_sqm,primary_zoning_code,primary_zoning_class,mixed_zoning_flag,heritage_flag,heritage_max_significance,bushfire_flag,bushfire_risk_level,flood_flag,primary_flood_class,distance_to_station_m,within_800m_catchment,assembly_opportunity_score
27560,3160513,WEROMBI ROAD GRASMERE,1.042479e+06,R5,Large Lot Residential,1,1,Local,1,3,0,None,10357.409447,0,0.0
42225,6229967,54 STUART STREET MULLUMBIMBY,9.232074e+02,R2,Low Density Residential,0,1,Local,0,0,0,None,37203.553789,0,0.0
34376,4435703,1 KELLY STREET WEABONGA,1.387220e+03,RU1,Primary Production,0,0,None,1,3,0,None,120317.207395,0,0.0
6818,742880,46 MIDDLESEX AVENUE GOROKAN,1.127372e+03,RE1,Public Recreation,1,0,None,1,2,0,None,5883.264069,0,0.0
42202,6227213,9 WILLIAM AVENUE CAMDEN,9.501617e+02,R2,Low Density Residential,0,1,Local,0,0,0,None,7828.701389,0,0.0
14008,1535253,2/3 HEMMINGS STREET PENRITH,1.472160e+03,RE1,Public Recreation,1,1,Local,0,0,0,None,909.878767,0,0.0
15203,1661513,17 ANNETTS PARADE MOSSY POINT,1.310728e+03,C2,Environmental Conservation,1,1,Local,1,3,0,None,142340.939821,0,0.0
27247,3113201,3 ALBUERA CLOSE MORPETH,2.972335e+03,R5,Large Lot Residential,0,1,State,1,1,0,None,4102.712473,0,0.0
18586,2041144,17 JAMES STREET MORPETH,1.193180e+03,R1,General Residential,0,1,Local,1,1,0,None,5332.507433,0,0.0
46664,7060444,10 ST HELEN STREET HOLMESVILLE,1.151573e+03,R2,Low Density Residential,0,1,Local,0,0,0,None,6051.544365,0,0.0
15196,1660252,3 STRATHMORE PARADE ROSEVILLE,8.500507e+02,R2,Low Density Residential,0,1,Local,0,0,0,None,1052.765035,0,0.0
46672,7061091,12 WILLIAM STREET HOLMESVILLE,4.485062e+03,R2,Low Density Residential,0,1,Local,1,3,0,None,5940.729957,0,0.0
42180,6222543,46 KINGSLEY LANE BYRON BAY,1.317885e+03,R2,Low Density Residential,0,1,Local,0,0,0,None,36486.810760,0,0.0
3595,388345,24 OSPREY DRIVE YAMBA,8.321820e+02,R2,Low Density Residential,0,0,None,0,0,1,Probable Maximum Flood Line,75625.913752,0,0.0
42171,6219110,50 BOWMAN STREET DRUMMOYNE,8.065381e+02,R2,Low Density Residential,0,1,Local,0,0,0,None,3342.055980,0,0.0
15190,1659636,2/61 AVALON PARADE AVALON BEACH,1.601637e+03,R2,Low Density Residential,0,1,Local,0,0,0,None,16319.847197,0,0.0
3607,389352,166 TURF STREET GRAFTON,9.236638e+02,R1,General Residential,0,0,None,0,0,1,Flood Planning Area,114820.898984,0,0.0
11329,1228968,7 WOLSELEY STREET HABERFIELD,1.010079e+03,R2,Low Density Residential,0,1,Local,0,0,0,None,1716.410472,0,0.0
6796,740686,7 HOBBS STREET QUEANBEYAN,7.036616e+02,R2,Low Density Residential,0,1,Local,0,0,0,None,97906.211899,0,0.0
46701,7065601,LAKE STREET LAKE CARGELLIGO,4.297681e+05,W2,Recreational Waterways,1,1,Local,1,3,0,None,357248.640946,0,0.0

In [8]:
for score_col in score_cols:
    print(f"\n=== {score_col} top 10% zoning distribution ===")
    cutoff = scored[score_col].quantile(0.9)
    top_df = scored[scored[score_col] >= cutoff]
    print(top_df["primary_zoning_code"].value_counts(dropna=False).head(15))

=== station_access_score top 10% zoning distribution ===
primary_zoning_code
R2      915
MU1     849
R3      647
R1      538
E1      441
R4      435
SP2     314
SP5     251
E2      249
RE1     141
C4       41
None     39
E4       31
E3       28
C2       19
Name: count, dtype: int64

=== single_dwelling_rebuild_score top 10% zoning distribution ===
primary_zoning_code
R2     4478
R1      762
RU5      20
R5       11
Name: count, dtype: int64

=== assembly_opportunity_score top 10% zoning distribution ===
primary_zoning_code
R4     1692
MU1    1166
R3      646
E1      482
R1      288
E2      283
E3      205
R2      179
SP5      77
Name: count, dtype: int64

=== granny_flat_score top 10% zoning distribution ===
primary_zoning_code
R2    4642
R1    1027
R5      87
Name: count, dtype: int64

=== land_bank_hold_score top 10% zoning distribution ===
primary_zoning_code
R4     1605
R3     1262
MU1    1112
E1      447
E2      260
R2      148
E3      148
SP5      93
R1       53
Name: count, dtype: int64

=== townhouse_multi_dwelling_score top 10% zoning distribution ===
primary_zoning_code
R3     1982
MU1    1361
R4     1178
R1      394
R2      129
Name: count, dtype: int64

=== low_rise_apartment_score top 10% zoning distribution ===
primary_zoning_code
R4     1685
MU1    1395
E1      565
R3      486
E2      350
SP5     167
SP2     136
E3       87
R2       72
R1       67
RE1      63
E4       22
DM        5
W1        3
SP3       3
Name: count, dtype: int64

=== dual_occupancy_score top 10% zoning distribution ===
primary_zoning_code
R2    3864
R1    1959
Name: count, dtype: int64

In [9]:
for score_col in score_cols:
    print(f"\n=== {score_col} top 10% lot size summary ===")
    cutoff = scored[score_col].quantile(0.9)
    top_df = scored[scored[score_col] >= cutoff]
    print(top_df["lot_size_proxy_sqm"].describe())

=== station_access_score top 10% lot size summary ===
count      4995.000000
mean       3923.148454
std       12892.842170
min           7.378215
25%         733.985514
50%        1302.485299
75%        3023.009171
max      267899.936628
Name: lot_size_proxy_sqm, dtype: float64

=== single_dwelling_rebuild_score top 10% lot size summary ===
count    5271.000000
mean     1412.495022
std       840.267322
min       800.004201
25%       904.052553
50%      1068.669828
75%      1472.324419
max      4999.121984
Name: lot_size_proxy_sqm, dtype: float64

=== assembly_opportunity_score top 10% lot size summary ===
count      5018.000000
mean       8064.644261
std       16724.909261
min          67.898191
25%        2438.347669
50%        4073.900365
75%        7545.073835
max      256852.562761
Name: lot_size_proxy_sqm, dtype: float64

=== granny_flat_score top 10% lot size summary ===
count    5.756000e+03
mean     6.633130e+03
std      7.732675e+04
min      1.000103e+03
25%      1.115250e+03
50%      1.426083e+03
75%      3.055027e+03
max      5.609438e+06
Name: lot_size_proxy_sqm, dtype: float64

=== land_bank_hold_score top 10% lot size summary ===
count      5128.000000
mean       6442.784728
std       14502.091186
min        1000.327709
25%        2042.285809
50%        3227.302816
75%        6207.887966
max      256852.562761
Name: lot_size_proxy_sqm, dtype: float64

=== townhouse_multi_dwelling_score top 10% lot size summary ===
count      5044.000000
mean       6552.087305
std       11842.476145
min         161.248278
25%        2233.732723
50%        3478.672257
75%        6583.151760
max      163632.269895
Name: lot_size_proxy_sqm, dtype: float64

=== low_rise_apartment_score top 10% lot size summary ===
count      5114.000000
mean       7466.954904
std       17970.669723
min          10.695870
25%        1764.606754
50%        3636.867755
75%        7591.522293
max      607234.813375
Name: lot_size_proxy_sqm, dtype: float64

=== dual_occupancy_score top 10% lot size summary ===
count      5823.000000
mean       6321.353399
std       19729.608739
min        1000.103133
25%        1375.423695
50%        1779.930110
75%        3698.598001
max      648281.698276
Name: lot_size_proxy_sqm, dtype: float64

In [10]:
for score_col in score_cols:
    print(f"\n=== {score_col} top 10% constraints ===")
    cutoff = scored[score_col].quantile(0.9)
    top_df = scored[scored[score_col] >= cutoff]

    print("heritage_flag:")
    print(top_df["heritage_flag"].value_counts(normalize=True, dropna=False))

    print("bushfire_risk_level:")
    print(top_df["bushfire_risk_level"].value_counts(normalize=True, dropna=False))

    print("flood_flag:")
    print(top_df["flood_flag"].value_counts(normalize=True, dropna=False))

=== station_access_score top 10% constraints ===
heritage_flag:
heritage_flag
0    0.706507
1    0.293493
Name: proportion, dtype: float64
bushfire_risk_level:
bushfire_risk_level
0    0.939740
1    0.044645
3    0.012813
2    0.002803
Name: proportion, dtype: float64
flood_flag:
flood_flag
0    0.9998
1    0.0002
Name: proportion, dtype: float64

=== single_dwelling_rebuild_score top 10% constraints ===
heritage_flag:
heritage_flag
0    1.0
Name: proportion, dtype: float64
bushfire_risk_level:
bushfire_risk_level
0    0.98672
1    0.01328
Name: proportion, dtype: float64
flood_flag:
flood_flag
0    1.0
Name: proportion, dtype: float64

=== assembly_opportunity_score top 10% constraints ===
heritage_flag:
heritage_flag
0    0.955361
1    0.044639
Name: proportion, dtype: float64
bushfire_risk_level:
bushfire_risk_level
0    0.965126
1    0.032284
2    0.001594
3    0.000996
Name: proportion, dtype: float64
flood_flag:
flood_flag
0    1.0
Name: proportion, dtype: float64

=== granny_flat_score top 10% constraints ===
heritage_flag:
heritage_flag
0    1.0
Name: proportion, dtype: float64
bushfire_risk_level:
bushfire_risk_level
0    0.951529
1    0.048124
2    0.000347
Name: proportion, dtype: float64
flood_flag:
flood_flag
0    1.0
Name: proportion, dtype: float64

=== land_bank_hold_score top 10% constraints ===
heritage_flag:
heritage_flag
0    0.960218
1    0.039782
Name: proportion, dtype: float64
bushfire_risk_level:
bushfire_risk_level
0    0.982059
1    0.016381
2    0.001365
3    0.000195
Name: proportion, dtype: float64
flood_flag:
flood_flag
0    1.0
Name: proportion, dtype: float64

=== townhouse_multi_dwelling_score top 10% constraints ===
heritage_flag:
heritage_flag
0    0.949048
1    0.050952
Name: proportion, dtype: float64
bushfire_risk_level:
bushfire_risk_level
0    0.970262
1    0.028549
3    0.000595
2    0.000595
Name: proportion, dtype: float64
flood_flag:
flood_flag
0    0.999009
1    0.000991
Name: proportion, dtype: float64

=== low_rise_apartment_score top 10% constraints ===
heritage_flag:
heritage_flag
0    0.964998
1    0.035002
Name: proportion, dtype: float64
bushfire_risk_level:
bushfire_risk_level
0    0.984552
1    0.013492
2    0.001369
3    0.000587
Name: proportion, dtype: float64
flood_flag:
flood_flag
0    1.0
Name: proportion, dtype: float64

=== dual_occupancy_score top 10% constraints ===
heritage_flag:
heritage_flag
0    1.0
Name: proportion, dtype: float64
bushfire_risk_level:
bushfire_risk_level
0    0.921518
1    0.078310
2    0.000172
Name: proportion, dtype: float64
flood_flag:
flood_flag
0    1.0
Name: proportion, dtype: float64

In [11]:
for score_col in score_cols:
    print(f"\n=== {score_col} top 10% accessibility ===")
    cutoff = scored[score_col].quantile(0.9)
    top_df = scored[scored[score_col] >= cutoff]

    print(top_df["distance_to_station_m"].describe())
    print(top_df["within_800m_catchment"].value_counts(normalize=True, dropna=False))

=== station_access_score top 10% accessibility ===
count    4995.000000
mean      230.369857
std        99.554629
min        14.787625
25%       151.286661
50%       233.895946
75%       316.214491
max       397.307850
Name: distance_to_station_m, dtype: float64
within_800m_catchment
1    1.0
Name: proportion, dtype: float64

=== single_dwelling_rebuild_score top 10% accessibility ===
count      5271.000000
mean       9694.033241
std       49352.324435
min          17.727628
25%         789.550308
50%        1261.954762
75%        1742.942724
max      858261.888728
Name: distance_to_station_m, dtype: float64
within_800m_catchment
0    0.746538
1    0.253462
Name: proportion, dtype: float64

=== assembly_opportunity_score top 10% accessibility ===
count      5018.000000
mean      10375.171572
std       47876.780811
min          20.279811
25%         359.765407
50%         657.419229
75%        1304.514784
max      925922.993021
Name: distance_to_station_m, dtype: float64
within_800m_catchment
1    0.588282
0    0.411718
Name: proportion, dtype: float64

=== granny_flat_score top 10% accessibility ===
count      5756.000000
mean      11430.884440
std       47956.004239
min          26.055536
25%         956.263346
50%        1723.836065
75%        2994.520350
max      632848.671985
Name: distance_to_station_m, dtype: float64
within_800m_catchment
0    0.805942
1    0.194058
Name: proportion, dtype: float64

=== land_bank_hold_score top 10% accessibility ===
count      5128.000000
mean       5162.357320
std       31011.345324
min          23.902681
25%         339.490327
50%         591.467860
75%        1052.363291
max      582417.561681
Name: distance_to_station_m, dtype: float64
within_800m_catchment
1    0.653666
0    0.346334
Name: proportion, dtype: float64

=== townhouse_multi_dwelling_score top 10% accessibility ===
count      5044.000000
mean      11498.433917
std       48123.730867
min          23.902681
25%         412.188704
50%         780.106882
75%        1691.148730
max      539856.880676
Name: distance_to_station_m, dtype: float64
within_800m_catchment
1    0.512094
0    0.487906
Name: proportion, dtype: float64

=== low_rise_apartment_score top 10% accessibility ===
count      5114.000000
mean       3341.520792
std       24728.788104
min          14.787625
25%         298.152581
50%         510.851853
75%         875.184547
max      467712.272241
Name: distance_to_station_m, dtype: float64
within_800m_catchment
1    0.722331
0    0.277669
Name: proportion, dtype: float64

=== dual_occupancy_score top 10% accessibility ===
count      5823.000000
mean      71538.732277
std      139925.395026
min          26.055536
25%        1221.572920
50%        2895.849784
75%       88674.532911
max      928104.723412
Name: distance_to_station_m, dtype: float64
within_800m_catchment
0    0.856775
1    0.143225
Name: proportion, dtype: float64

In [12]:
weird_apartment = scored[
    (scored["low_rise_apartment_score"] >= 70)
    & (
        scored["primary_zoning_code"].isin(["R2", "RU1", "RU4", "C2", "C3", "C4", "RE1"])
        | (scored["heritage_flag"] == 1)
        | (scored["flood_flag"] == 1)
    )
]

weird_apartment[base_cols + ["low_rise_apartment_score"]].head(30)

,RID,address,lot_size_proxy_sqm,primary_zoning_code,primary_zoning_class,mixed_zoning_flag,heritage_flag,heritage_max_significance,bushfire_flag,bushfire_risk_level,flood_flag,primary_flood_class,distance_to_station_m,within_800m_catchment,low_rise_apartment_score
3989,433777,202/11-19 WAITARA AVENUE WAITARA,10560.722616,E1,Local Centre,1,1,Local,0,0,0,None,195.915087,1,71.5
3990,433807,410/11-19 WAITARA AVENUE WAITARA,10560.722616,E1,Local Centre,1,1,Local,0,0,0,None,195.915087,1,71.5
7490,816349,7/27 JOHN STREET WATERLOO,17884.171183,E1,Local Centre,1,1,Local,0,0,0,None,346.332557,1,71.5
7491,816395,31/63 MCEVOY STREET WATERLOO,17884.171183,E1,Local Centre,1,1,Local,0,0,0,None,346.332557,1,71.5
11447,1241927,83-85 WONIORA ROAD HURSTVILLE,5020.051898,R4,High Density Residential,1,1,Local,0,0,0,None,479.610040,1,71.5
14997,1639514,17D/50 WHALING ROAD NORTH SYDNEY,7803.507436,R4,High Density Residential,1,1,Local,0,0,0,None,624.439954,1,71.5
14998,1639525,13C/50 WHALING ROAD NORTH SYDNEY,7803.507436,R4,High Density Residential,1,1,Local,0,0,0,None,624.439954,1,71.5
19234,2108601,69/2A HENRY LAWSON AVENUE MCMAHONS POINT,6921.393070,R4,High Density Residential,1,1,Local,0,0,0,None,733.208337,1,71.5
19235,2108602,70/2A HENRY LAWSON AVENUE MCMAHONS POINT,6921.393070,R4,High Density Residential,1,1,Local,0,0,0,None,733.208337,1,71.5
21850,2392688,1203/1 MACQUARIE PLACE SYDNEY,7546.237555,SP5,Metropolitan Centre,1,1,Local,0,0,0,None,151.825474,1,71.5
21851,2392721,4502/1 MACQUARIE PLACE SYDNEY,7546.237555,SP5,Metropolitan Centre,1,1,Local,0,0,0,None,151.825474,1,71.5
21852,2392745,524/1 MACQUARIE PLACE SYDNEY,7546.237555,SP5,Metropolitan Centre,1,1,Local,0,0,0,None,151.825474,1,71.5
21853,2392758,601/1 MACQUARIE PLACE SYDNEY,7546.237555,SP5,Metropolitan Centre,1,1,Local,0,0,0,None,151.825474,1,71.5
22674,2489158,60/78 MARCH STREET RICHMOND,48767.368961,E2,Commercial Centre,1,1,Local,0,0,0,None,241.336360,1,71.5
23308,2575916,16/47 WONIORA ROAD HURSTVILLE,6349.031623,R4,High Density Residential,1,1,Local,0,0,0,None,237.745404,1,71.5
24363,2722217,33/282 DUNMORE STREET PENDLE HILL,24794.619139,R4,High Density Residential,1,1,Local,0,0,0,None,604.292474,1,71.5
25390,2862834,61/8 RENWICK STREET REDFERN,5193.615479,MU1,Mixed Use,1,1,Local,0,0,0,None,271.030564,1,71.5
25794,2913823,73B NEW SOUTH HEAD ROAD PADDINGTON,5385.860571,MU1,Mixed Use,1,1,Local,0,0,0,None,707.152671,1,71.5
27763,3195584,95 PENDLE WAY PENDLE HILL,11849.448912,R4,High Density Residential,1,1,Local,0,0,0,None,474.135663,1,71.5
28970,3358737,99/1-5 ALEXANDRIA PARADE WAITARA,9040.789337,R4,High Density Residential,1,1,Local,0,0,0,None,306.223056,1,71.5
28971,3358754,82/1-5 ALEXANDRIA PARADE WAITARA,9040.789337,R4,High Density Residential,1,1,Local,0,0,0,None,306.223056,1,71.5
28972,3358827,9/6-10 ROMSEY STREET WAITARA,9040.789337,R4,High Density Residential,1,1,Local,0,0,0,None,306.223056,1,71.5
34075,4350082,13/5-17 QUEEN STREET NEWTOWN,7255.020753,E1,Local Centre,1,1,Local,0,0,0,None,94.751100,1,71.5
34130,4364746,106/1A TURNER STREET REDFERN,6844.738047,MU1,Mixed Use,1,1,Local,0,0,0,None,191.489912,1,71.5
34543,4497081,916G/780 BOURKE STREET REDFERN,6424.381146,E1,Local Centre,1,1,Local,0,0,0,None,695.416898,1,71.5
34575,4505581,8C/3-17 DARLING POINT ROAD DARLING POINT,13467.163228,MU1,Mixed Use,1,1,Local,0,0,0,None,219.581580,1,71.5
34576,4505598,4E/3-17 DARLING POINT ROAD DARLING POINT,13467.163228,MU1,Mixed Use,1,1,Local,0,0,0,None,219.581580,1,71.5
35802,4765411,47/11 THE BOULEVARDE STRATHFIELD,16376.835175,E2,Commercial Centre,1,1,Local,0,0,0,None,215.632070,1,71.5
36013,4794353,2052/236 PACIFIC HIGHWAY HORNSBY,42728.703309,R4,High Density Residential,1,1,Local,0,0,0,None,265.458599,1,71.5
36014,4794378,2077/236 PACIFIC HIGHWAY HORNSBY,42728.703309,R4,High Density Residential,1,1,Local,0,0,0,None,265.458599,1,71.5

In [13]:
missed_apartment = scored[
    (scored["primary_zoning_code"].isin(["MU1", "R4", "SP5", "E1", "E2"]))
    & (scored["lot_size_proxy_sqm"] >= 2000)
    & (scored["distance_to_station_m"] <= 2000)
    & (scored["low_rise_apartment_score"] < 50)
]

missed_apartment[base_cols + ["low_rise_apartment_score"]].head(30)

,RID,address,lot_size_proxy_sqm,primary_zoning_code,primary_zoning_class,mixed_zoning_flag,heritage_flag,heritage_max_significance,bushfire_flag,bushfire_risk_level,flood_flag,primary_flood_class,distance_to_station_m,within_800m_catchment,low_rise_apartment_score
549,59216,4 LINDEL PLACE LINDFIELD,2414.556424,R4,High Density Residential,0,1,Local,0,0,0,None,575.980655,1,46.5
1069,114420,1 CIVIC ROAD AUBURN,2099.841235,E1,Local Centre,0,1,Local,0,0,0,None,258.633627,1,46.5
1401,154514,275/398-408 PITT STREET HAYMARKET,3138.361167,SP5,Metropolitan Centre,0,1,Local,0,0,0,None,332.129774,1,46.5
1402,154515,274/398-408 PITT STREET HAYMARKET,3138.361167,SP5,Metropolitan Centre,0,1,Local,0,0,0,None,332.129774,1,46.5
1403,154522,267/398-408 PITT STREET HAYMARKET,3138.361167,SP5,Metropolitan Centre,0,1,Local,0,0,0,None,332.129774,1,46.5
1525,167863,5/1 O'CONNELL STREET SYDNEY,4604.544570,SP5,Metropolitan Centre,0,1,Local,0,0,0,None,413.994126,1,46.5
1745,189678,16/10-14 CALLIOPE STREET GUILDFORD,3317.848230,R4,High Density Residential,0,1,Local,0,0,0,None,259.632672,1,46.5
2140,233045,12/26-32 PYRMONT BRIDGE ROAD PYRMONT,2217.836466,MU1,Mixed Use,1,1,Local,0,0,0,None,1274.349092,0,41.0
2652,283523,43/10-12 RAY STREET TURRAMURRA,4665.257349,R4,High Density Residential,0,1,Local,0,0,0,None,252.849644,1,46.5
2653,283556,10/10-12 RAY STREET TURRAMURRA,4665.257349,R4,High Density Residential,0,1,Local,0,0,0,None,252.849644,1,46.5
4010,436183,21/176 SOUTH PARADE AUBURN,2154.979300,E1,Local Centre,0,1,Local,0,0,0,None,265.573329,1,46.5
4521,493213,101/48-50 ALFRED STREET SOUTH MILSONS POINT,3376.421417,MU1,Mixed Use,0,1,Local,0,0,0,None,218.116278,1,46.5
4522,493285,10B/48-50 ALFRED STREET SOUTH MILSONS POINT,3376.421417,MU1,Mixed Use,0,1,Local,0,0,0,None,218.116278,1,46.5
4855,533073,11/2A SHIRLEY ROAD ROSEVILLE,3579.708872,R4,High Density Residential,0,1,Local,0,0,0,None,314.963167,1,46.5
5265,576572,34/103 MAJORS BAY ROAD CONCORD,2039.455319,MU1,Mixed Use,0,1,Local,0,0,0,None,1793.424715,0,36.0
5522,604745,78 RAILWAY PARADE LEURA,3421.764843,E1,Local Centre,1,1,Local,1,2,0,None,101.698275,1,38.3
5968,654233,16 CALLIOPE STREET GUILDFORD,2072.366697,R4,High Density Residential,0,1,Local,0,0,0,None,292.529743,1,46.5
6419,703360,4/3 HILL STREET ROSEVILLE,2524.675923,R4,High Density Residential,0,1,Local,0,0,0,None,289.051867,1,46.5
6563,719558,602/4 RAVENSHAW STREET NEWCASTLE WEST,2326.380715,R4,High Density Residential,0,1,Local,0,0,0,None,901.640637,0,36.0
7033,765617,505/57 UPPER PITT STREET KIRRIBILLI,3161.975016,R4,High Density Residential,0,1,Local,0,0,0,None,619.822156,1,46.5
7363,803221,46/40-46 PENKIVIL STREET BONDI,4276.577574,R4,High Density Residential,0,1,Local,0,0,0,None,330.591054,1,46.5
7364,803265,2/40-46 PENKIVIL STREET BONDI,4276.577574,R4,High Density Residential,0,1,Local,0,0,0,None,330.591054,1,46.5
7399,806535,602/199 REGENT STREET REDFERN,3701.318489,MU1,Mixed Use,0,1,Local,0,0,0,None,171.597785,1,46.5
7400,806644,1G/199 REGENT STREET REDFERN,3701.318489,MU1,Mixed Use,0,1,Local,0,0,0,None,171.597785,1,46.5
7768,848503,4/211-215 DUNMORE STREET PENDLE HILL,2946.857913,R4,High Density Residential,0,1,Local,0,0,0,None,642.800954,1,46.5
8519,931278,91/10 JAQUES AVENUE BONDI BEACH,3237.776430,E1,Local Centre,0,1,Local,0,0,0,None,239.989199,1,46.5
8520,931281,88/10 JAQUES AVENUE BONDI BEACH,3237.776430,E1,Local Centre,0,1,Local,0,0,0,None,239.989199,1,46.5
8549,934183,2/3 MARIAN STREET KILLARA,2114.415587,E1,Local Centre,0,1,Local,0,0,0,None,108.717399,1,46.5
11649,1268095,3007/343-357 PITT STREET SYDNEY,2114.600586,SP5,Metropolitan Centre,0,1,Local,0,0,0,None,260.605350,1,46.5
11650,1268227,1201/343-357 PITT STREET SYDNEY,2114.600586,SP5,Metropolitan Centre,0,1,Local,0,0,0,None,260.605350,1,46.5

In [14]:
Path("../../data/processed/site_features").mkdir(parents=True, exist_ok=True)

scored.to_parquet(
    "../../data/processed/site_features/property_site_features_v1_sample_scored.parquet",
    index=False
)